### ISSUE TITLE
what is this variable for? and the next one?

### ISSUE THREAD

**Issue by tatacoa** [DataVis-SuperstRs/First-Explorations#2]
https://github.com/DataVis-SuperstRs/First-Explorations/blob/bfbd079996ee93dec3c61aceb3c98cb55e5a5837/LabDistances.R#L39

some how we manage to compute the color distance thing, but we get different results... check the file color distances please :*

**Comment by jabusch24** [comment]
Checked your file! You are using CIE76 formula. According to wikipedia it's the older, outdated version (how could this possibly outdated...hm).
I used CIE94 which is really complex, but i really just copy pasted the formulas off wikipedia. 

I created the CompareCIE.R file to run a comparison to see, how much different it is. It seems it is not that different, so in the later steps, we'ld just have to decide for which on to go in the future. 

Tho the comparison showed an interesting outlier that we should look at more closely. 

P.S.: regarding the variables, Wiki explains: 
[https://en.wikipedia.org/wiki/Color_difference#CIE94](url)

> weighting factors kL, K1 and K2 depend on the application
